### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [lzfelix/pyTetris#1]
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./gui.py:25:21: E999 SyntaxError: invalid syntax
    print AREA_MIDDLE
                    ^
./pyTetris.py:30:38: E999 SyntaxError: invalid syntax
        print "Working on yx: %d x %d" % (self.DISPLAY_H, self.DISPLAY_W)
                                     ^
2     E999 SyntaxError: invalid syntax
2
```

**Comment by lzfelix** [comment]
My apologies, but given the existence of your repository named [itinerant-tester](https://github.com/cclauss/itinerant-tester) and the pattern of opened issues and pull requests, I'm inclined to ask: are you a human or a robot?

**[EDIT]**
Well, it seems that I have already got my answer from [here](https://github.com/cclauss/itinerant-tester/commit/b8a9212524f9ad33cc8ee3c0bbb3388ff07111b7).

**Comment by cclauss** [comment]
A human but a crazy one...

**Comment by lzfelix** [comment]
Well, actually this code requires Python 2.x.
